<a href="https://colab.research.google.com/github/park-hyun-wook/Chungnam_automobile_course_0623/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy 시작하기

NumPy란 무엇인가요?
NumPy는 배열을 다루는 데 사용되는 Python 라이브러리입니다.

또한 선형 대수, 푸리에 변환, 행렬의 영역에서 작업하기 위한 함수도 갖추고 있습니다.


왜 NumPy를 사용해야 하나요?
파이썬에서는 배열의 역할을 하는 리스트가 있지만, 처리 속도가 느립니다.

NumPy는 기존 Python 리스
트보다 최대 50배 빠른 배열 객체를 제공하는 것을 목표로 합니다.

NumPy의 배열 객체는 라고 불리며 ndarray, 작업을 매우 쉽게 만드는 많은 지원 함수를 제공합니다 ndarray.

In [1]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


NumPy 버전 확인
버전 문자열은 __version__ 속성에 저장됩니다.

In [2]:
import numpy as np

print(np.__version__)

2.0.2


NumPy 배열 생성

NumPy ndarray 객체 생성
NumPy는 배열을 다루는 데 사용됩니다. NumPy의 배열 객체는 ndarray.

ndarray함수를 사용하여 NumPy 객체를 생성할 수 있습니다 array().

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


type(): 이 Python 내장 함수는 전달된 객체의 타입을 알려줍니다. 위 코드처럼 객체의 타입을 보여 arr줍니다




numpy.ndarray.를 생성하려면 ndarray목록, 튜플 또는 배열과 같은 객체를 메서드에 전달하면 array() 다음과 같이 변환됩니다 ndarray.

튜플을 사용하여 NumPy 배열을 생성합니다.

In [4]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


배열의 차원
배열의 차원은 배열 깊이(중첩 배열)의 한 수준입니다.

중첩 배열: 배열을 요소로 갖는 배열입니다.

NumPy 배열 인덱싱

배열 요소에 액세스
배열 인덱싱은 배열 요소에 액세스하는 것과 같습니다.

배열 요소에 접근하려면 인덱스 번호를 참조하면 됩니다.

NumPy 배열의 인덱스는 0부터 시작합니다. 즉, 첫 번째 요소의 인덱스는 0이고, 두 번째 요소의 인덱스는 1입니다.

예나만의 Python 서버를 얻으세요
다음 배열에서 첫 번째 요소를 가져옵니다.

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


다음 배열에서 두 번째 요소를 가져옵니다.

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


다음 배열에서 세 번째와 네 번째 요소를 가져와 추가합니다.

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


2차원 배열에 접근하기
2차원 배열의 요소에 접근하려면 차원과 요소의 인덱스를 나타내는 쉼표로 구분된 정수를 사용할 수 있습니다.

2차원 배열은 행과 열이 있는 표와 같다고 생각하시면 됩니다. 여기서 차원은 행을 나타내고 인덱스는 열을 나타냅니다.

첫 번째 행, 두 번째 열의 요소에 접근합니다.

In [8]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


2번째 행, 5번째 열의 요소에 접근합니다.

In [9]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


3차원 배열에 접근
3차원 배열의 요소에 접근하려면 차원과 요소의 인덱스를 나타내는 쉼표로 구분된 정수를 사용할 수 있습니다.

첫 번째 배열의 두 번째 배열의 세 번째 요소에 접근합니다.

In [10]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


예시 설명
arr[0, 1, 2]값을 출력합니다 6.

그 이유는 다음과 같습니다.

첫 번째 숫자는 두 개의 배열
[[1, 2, 3], [4, 5, 6]]
과
[[7, 8, 9], [10, 11, 12]] 을 포함하는 첫 번째 차원을 나타
냅니다. 를 선택했으므로 0첫 번째 배열
[[1, 2, 3], [4, 5, 6]]이 남습니다.

두 번째 숫자는 두 개의 배열
[1, 2, 3]
과
[4, 5, 6] 을 포함하는 두 번째 차원을 나타냅니다.
를 선택했으므로 두 번째 배열 [4, 5, 6]이 1남습니다.

세 번째 숫자는 세 개의 값(
4,
5,
6) 을 포함하는 세 번째 차원을 나타냅니다.
를 선택했으므로 세 번째 값( 6) 2이 됩니다.

음수 인덱싱
배열의 끝에서 접근하려면 음수 인덱싱을 사용합니다.

2번째 차원의 마지막 요소를 출력합니다.

In [11]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


NumPy 배열 슬라이싱

배열 슬라이싱
파이썬에서 슬라이싱은 주어진 인덱스에서 다른 주어진 인덱스로 요소를 옮기는 것을 의미합니다.

인덱스 대신 슬라이스를 이렇게 전달합니다: .[start:end]

다음과 같이 단계를 정의할 수도 있습니다 .[start:end:step]

시작을 통과하지 못하면 0으로 간주됩니다.

우리가 end를 전달하지 않으면 해당 차원의 배열의 길이가 고려됩니다.

만약 우리가 단계를 통과하지 못한다면 그것은 1로 간주됩니다

다음 배열에서 인덱스 1부터 인덱스 5까지의 요소를 슬라이스합니다.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

참고: 결과 에 시작 인덱스는 포함되지만 , 끝 인덱스는 제외됩니다 .

배열의 인덱스 4부터 끝까지 요소를 슬라이스합니다.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

시작부터 인덱스 4까지 요소를 슬라이스합니다(포함되지 않음):

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

네거티브 슬라이싱
빼기 연산자를 사용하여 끝에서부터 인덱스를 참조합니다.

끝에서 3번째 인덱스부터 끝에서 1번째 인덱스까지 슬라이스합니다.

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


단계
값을 사용하여 step슬라이싱 단계를 결정합니다.

인덱스 1부터 인덱스 5까지 다른 모든 요소를 ​​반환합니다.

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])